apiVersion: v1
kind: Service
metadata:
  name: techno-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-security-groups: sg-08aaeebe87bd4ba30
spec:
  type: LoadBalancer
  selector:
    app: techno-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 2000