apiVersion: v1
kind: Service
metadata:
  name: my-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-security-groups: sg-01624911488373b4b
spec:
  type: LoadBalancer
  selector:
    app: techno-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 2000
