apiVersion: apps/v1
kind: Deployment
metadata:
  name: techno-deployment
  labels:
    app: techno-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: techno-app
  template:
    metadata:
      labels:
        app: techno-app
    spec:
      containers:
        - name: techno-container
          image: 126189343233.dkr.ecr.us-east-1.amazonaws.com/techno-ecr-payakumbuh-akbar:dev
          ports:
            - containerPort: 2000
          env:
           env:
            - name: AWS_ACCESS_KEY_ID
              value: "${AWS_ACCESS_KEY_ID}"
            - name: AWS_SECRET_ACCESS_KEY
              value: "${AWS_SECRET_ACCESS_KEY}"
            - name: AWS_REGION
              value: "${AWS_REGION}"
            - name: FLASK_SECRET_KEY
              value: "${FLASK_SECRET_KEY}"
            - name: ATHENA_DB
              value: "rekognition_results_db"
            - name: S3_STAGING_DIR
              value: "s3://technoinput-payakumbuh-akbar"
            - name: FLASK_SECRET_KEY
              value: "lks"
            - name: API_GATEWAY_URL
              value: "https://hd8kk4av44.execute-api.us-east-1.amazonaws.com/dev"
            - name: SNS_TOPIC_ARN
              value: "arn:aws:sns:us-east-1:126189343233:techno-sns-payakumbuh-akbar"
            - name: ATHENA_SCHEMA_NAME
              value: "rekognition_result"